plugins {
    java
    alias(libs.plugins.shadow)
}


dependencies {
    compileOnly(libs.jspecify)

    implementation("com.squareup.moshi:moshi:1.8.0") // Latest version not using Kotlin via okio
    implementation("com.squareup.okhttp3:okhttp:3.14.9") // Latest version not using Kotlin
    implementation("org.slf4j:slf4j-api:1.4.3") // Oldest version possible for maximum compatibility

    testRuntimeOnly(libs.slf4j.simple)

    testFixturesApi(libs.junit.jupiter.api)
    testFixturesApi(libs.assertj)

    testFixturesImplementation("io.javalin:javalin:4.6.8") // Latest version still supporting java 8

    testFixturesRuntimeOnly(libs.junit.jupiter)
    testFixturesRuntimeOnly(libs.junit.platform.launcher)
}

configurations {
    testFixturesApi {
        extendsFrom(configurations.compileOnly.get())
        extendsFrom(configurations.implementation.get())
    }
}

val generateBuildManifest = tasks.register("generateBuildManifest") {
    description = "Generate BuildManifest.java"
    val outputDir = layout.buildDirectory.dir("generated/sources/buildManifest/java")
    outputs.dir(outputDir)

    doLast {
        val out = outputDir.get().asFile
        val pkgDir = out.resolve("com/zalphion/featurecontrol")
        pkgDir.mkdirs()

        pkgDir.resolve("BuildManifest.java").writeText(
            """
            package com.zalphion.featurecontrol;

            /**
             * Generated by Gradle
             */
            public class BuildManifest {
                public static final String platform = "${project.findProperty("POM_DEVELOPER_ID")}/FeatureControl-${project.findProperty("POM_ARTIFACT_ID")}";
                public static final String version = "${project.findProperty("PROJECT_VERSION_NAME") ?: "snapshot"}";
                public static final String repositoryUrl = "${project.findProperty("POM_URL")}";
            }
            """.trimIndent()
        )
    }
}

configure<SourceSetContainer> {
    getByName("main").java.srcDir(layout.buildDirectory.dir("generated/sources/buildManifest/java"))
}

tasks.named("compileJava") {
    dependsOn(generateBuildManifest)
}

tasks.shadowJar {
    // replace original JAR for maven distribution
    archiveClassifier.set("")

    // relocate implementation dependencies
    relocate("com.squareup.moshi", "com.zalphion.featurecontrol.lib.moshi")
    relocate("okhttp", "com.zalphion.featurecontrol.lib.okhttp")
    relocate("okio", "com.zalphion.featurecontrol.lib.okio")

    // don't vendor slf4j-api
    dependencies {
        exclude(dependency("org.slf4j:slf4j-api:.*"))
    }

    // include project license
    from(rootProject.file("LICENSE")) {
        into("")
    }

    // remove unused vendored code
    minimize()
}