[versions]
junit = "5.8.2"

[plugins]
catalog-update = "nl.littlerobots.version-catalog-update:1.1.0"
lombok = "io.freefair.lombok:9.5.0"
maven-publish = "com.vanniktech.maven.publish:0.36.0"
shadow = "com.gradleup.shadow:9.4.1"

[libraries]
assertj = "org.assertj:assertj-core:3.27.7"
jspecify = "org.jspecify:jspecify:1.0.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.8.2"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.0"
